#!/bin/bash

maven=$(which mvn)
#projects="jeux-ejb jeux-web jeux-ear"
goals="clean install"
jboss_deployment_dir="$OPENSHIFT_JBOSSAS_DIR/standalone/deployments"

#mkdir -p $OPENSHIFT_DATA_DIR/m2/repository
#echo -e "<settings><localRepository>$OPENSHIFT_DATA_DIR/m2/repository</localRepository>\n</settings>\n" > $OPENSHIFT_DATA_DIR/settings.xml

cd $OPENSHIFT_REPO_DIR
$maven -f jeux-ejb/pom.xml $goals
# set via "rhc set env key=value -a appname"
$maven -f jeux-web/pom.xml -DserverSecret="$JEUX_SERVER_SECRET" $goals
$maven -f jeux-ear/pom.xml $goals

# trigger undeploy
prev_artifact=$(find $OPENSHIFT_JBOSSAS_DIR/standalone/deployments -name 'jeux*.ear' | head -1)
rm -f ${prev_artifact}*

curr_version="$($maven -f jeux-ear/pom.xml org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | egrep '^[0-9]+\.[0-9]+\.[0-9]+.*')"
artifact="$OPENSHIFT_HOMEDIR/.m2/repository/de/fhb/jeux-ear/$curr_version/jeux-ear-$curr_version.ear"

# deploy
cp -v $artifact $jboss_deployment_dir/

