#%RAML 0.8
---
# RAML (RESTful API Modeling Language) specification for Jeux.
#
# Cf. http://raml.org and https://github.com/raml-org/raml-spec
# for further information.

title: Jeux REST API
version: v1
baseUri: http://localhost:8080/JeuxWeb

/rest/v1:
    /status:
        get:
            description: |
                Get current API status ("ping" it).
            mediaType: text/plain
            responses:
                200:
                    body:
                        text/plain:
                            "OK"
                    description: |
                        All's well. So far.

/rest/v1:
    /groups:
        get:
            description: |
                Get all groups from DB as plain text.
            mediaType: text/plain
            responses:
                200:
                    body:
                        text/plain:
                            example: |
                                "'Some test group' (ID 1), round 1, active = true, completed = false, 1-1 sets
                                 'Sweede Grubbe' (ID 2), round 1, active = true, completed = false, 2-3 sets"
                                 
/rest/v1:
    /groups-json:
        get:
            description: |
                Get all groups from DB as JSON.
            mediaType: application/json
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                [
                                   {
                                      "id":1,
                                      "name":"Some test group",
                                      "roundId":1,
                                      "minSets":1,
                                      "maxSets":1,
                                      "active":true,
                                      "completed":false
                                   },
                                   {
                                      "id":2,
                                      "name":"Sweede Grubbe",
                                      "roundId":1,
                                      "minSets":2,
                                      "maxSets":3,
                                      "active":true,
                                      "completed":false
                                   }
                               ]

/rest/v1:
    /delete-group/{groupId}:
        delete:
            description: |
                Delete DB entry for group with given ID = {groupId}.

/create-group:
    put:
        description: |
            Send data representing a group object to be created on the server.
        body:
            application/json:
                example: |
                    {
                        maxSets:"3",
                        minSets:"2",
                        name:"Nuevo grupo",
                        round:"1",
                        active:true,
                        completed:false
                    }
         responses:
            201:
                description: |
                    Group object has been successfully created on the server.
            500:
                description: |
                    Failure to create group object server-side.
                    Reasons include: com.google.gson.Json(IO|Parse|Syntax)Exception, Exception



CONSIDERED DEPRECATED FOR THE TIME BEING:

/create-players:
    put:
        description: |
            Send data representing array of player objects to be created on the server.
        body:
            application/json:
                example: |
                    [
                       {
                          "name":"Player Two",
                          "groupName":"Group 2"
                       },
                       {
                          "name":"Player One",
                          "groupName":"Group 2"
                       }
                    ]
        responses:
            201:
                description: |
                    Player objects have been successfully created on the server.
            500:
                description: |
                    Failure to create player objects server-side.
                    Reasons include: com.google.gson.Json(IO|Parse|Syntax)Exception, Exception

